export const DATE_INPUT_BACK = 'DATE_INPUT/BACK';
export const DATE_INPUT_NEXT = 'DATE_INPUT/NEXT';

export const DATE_INPUT_MONTH = 'DATE_INPUT/MONTH';
export const DATE_INPUT_WEEKDAY = 'DATE_INPUT/WEEKDAY';
export const DATE_INPUT_DAY = 'DATE_INPUT/DAY';